version: '3.7'
services:
  ohx-addon-name:
    ports:
    - "5000:5000"
    volumes:
    - logvolume01:/var/log
    depends_on:
    - mqttbroker
  mqttbroker:
    volumes:
    - logvolume01:/var/log
    ports:
    - "1883:1883"
volumes:
  logvolume01: {}
metadata:
  name: ohx-addon-name
  version: "1.0"
  type: binding
  authors: ["your name"]
  title: "My addon"
  titles:
    de: "A translated title"
  description: "A long description that *may* use markdown and \n line breaks"
  manufacturers: ["Samsong"]
  products: ["XT-1247"]
  permissions:
    mandatory: ["HW_BLUETOOTH"]
    optional: []
  status:
    code: AVAILABLE
  estimated_memory_mb:
    min: 20
    max: 50
  homepage: "https://example.com"
  github: "https://github.com/my/repository"